### ISSUE TITLE
Model not saving

### ISSUE THREAD

**Issue by Sydriax** [255BITS/HyperGAN#52] opened 2017-03-07 01:26 UTC
I've had a model training for a few days set to periodically save, but to my disappointment, there's no model.ckpt anywhere on disc.

I'm using the tensorflow-1.0 branch on an AWS p2.xlarge instance. I did have to make a single modification in order to get it to not immediately break -- I believe I had to copy several of the regularizers from the main branch into the tensorflow-1.0 branch, but otherwise it's unmodified.

The issue is of course primarily that it's not actually saving, but I have a second question: is there anything at all that I can do to save the model presently running? I'd really rather not waste so much time and money if possible (though of course if there's nothing to be done I understand; I should have verified earlier that it was saving).

**Comment by martyn** [comment] 2017-03-07 03:58
It should be saving every 10k steps by default.  The saves by default are in `~/.hypergan/saves/<config>'.

This is on `master`.  The other branches aren't used right now.  I'll clean up the stray branches to prevent confusion in the future.

**Comment by Sydriax** [comment] 2017-03-07 04:02
I needed to use the tensorflow-1.0 branch in order to get it to work with my newer version of Tensorflow (remember issue #47?). It was configured to save every 10k steps, and it is generating the model.ckpt.meta file, so it's clearly attempting to save in some form. It's clearly just not doing it right.

**Comment by martyn** [comment] 2017-03-07 04:14
Oh I see, I'm sorry for the confusion.  `master` should work with the latest version of Tensorflow now.  The ``tensorflow-1.0` branch is outdated.

The fact that there's a model.ckpt.meta makes me think it's using pre-0.8 saving/loading code.  My fear is that the graph construction/configuration might also be different.  I'm not sure keeping the model is possible.

**Comment by Sydriax** [comment] 2017-03-07 04:15
Alas, it's as I feared. Thanks so much for your prompt response!

**Comment by Sydriax** [comment] 2017-03-07 13:03
Update: I stopped it, switched to master, pulled, re-ran setup.py develop, ran it, and... still no model.ckpt file.
I'm still getting the following four files in the directory:

checkpoint (this is just a text file which contains a path to a nonexistent model.ckpt file).
model.ckpt.data-00000-of-00001
model.ckpt.index
model.ckpt.meta

**Comment by Sydriax** [comment] 2017-03-07 13:18
Newest update: apparently the existence of a model.ckpt.meta doesn't indicate that it's using pre-0.8 saving/loading code, since it's attempting to load it anyway, but now I get the following error:

InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [49,8192] rhs shape= [49,15360]
         [[Node: save/Assign_153 = Assign[T=DT_FLOAT, _class=["loc:@generator/g_lin_proj/Matrix"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](generator/g_lin_proj/Matrix/RMSProp, save/RestoreV2_153/_227)]

**Comment by martyn** [comment] 2017-03-09 18:20
Reopening since I didn't realize this was still an issue.  Can you post your training command?  I can't reproduce yet.

In regards to model.ckpt - this file shouldn't exist in 0.8.  Saves should be located in `~/.hypergan/saves/<config>/`.

Can you also do a `git rev-parse HEAD` so that we're looking at the same commit?  I'm testing on master `ae72d858782ef87cecaedc4a65639cef8592acbd`.

**Comment by Sydriax** [comment] 2017-03-10 01:22
I'm on `c622b45562a8f675b390001a1247ea053b6b7a10`.

model.ckpt does not exist in the version I'm on. However, model.ckpt.meta does exist.
From your earlier quote: "The fact that there's a model.ckpt.meta makes me think it's using pre-0.8 saving/loading code." -- this was the main source of my concern. I've now successfully gotten it to load a model once, but it doesn't seem to be hugely consistent (it wouldn't load off of a different save).

**Comment by martyn** [comment] 2017-03-10 03:08
Interesting, I haven't had any save/load issues for a while.  I want to get to the bottom of this - training a model and it not loading the save is so frustrating.

Any idea how to reproduce?  That revision looks ok from what I can tell.  Also make sure no extra versions of hg are installed (pip3 uninstall hypergan; python3 setup.py develop)

I should have been clearer with my earlier message.  My (0.8) save folder looks like this:
```bash
❯ ls -la ~/.hypergan/saves/faces-lsgan/              
total 192140
drwxrwxr-x 2 martyn martyn      4096 Feb 28 09:11 .
drwxrwxr-x 9 martyn martyn     12288 Mar  8 19:48 ..
-rw-rw-r-- 1 martyn martyn       159 Feb 28 09:11 checkpoint
-rw-rw-r-- 1 martyn martyn 160301836 Feb 28 09:11 model.ckpt.data-00000-of-00001
-rw-rw-r-- 1 martyn martyn      6705 Feb 28 09:11 model.ckpt.index
-rw-rw-r-- 1 martyn martyn  36410109 Feb 28 09:11 model.ckpt.meta

```

**Comment by martyn** [comment] 2017-03-14 07:08
Closing this for now - can't reproduce.  If it occurs again lets create a new ticket.

**Closed by martyn** 2017-03-14 07:08 UTC
